export interface FaqItem {
  id: string
  question: string
  answer: string
}

/** The twelve questions from the product brief. Answers are short and say what is simulated in this demo. */
export const faqItems: FaqItem[] = [
  {
    id: "auto-record",
    question: "Does WIT automatically record meetings?",
    answer:
      "No. WIT does not automatically schedule, join, record or capture your meetings. Your calendar gives WIT context about what is coming up, and you start every capture yourself.",
  },
  {
    id: "choose-meetings",
    question: "Can I choose which meetings to capture?",
    answer:
      "Yes. You decide meeting by meeting. During setup you can choose to make all calendar meetings available for manual capture, pick certain kinds of meetings, or choose manually every time. Manual is the default.",
  },
  {
    id: "google-calendar",
    question: "Does WIT work with Google Calendar?",
    answer:
      "Yes. WIT is designed around Google Calendar and Google sign-in. In this demo build the connection is simulated, so no real calendar data is accessed.",
  },
  {
    id: "calendar-access",
    question: "Why does WIT need calendar access?",
    answer:
      "To show your upcoming meetings and to know which meeting a capture belongs to. WIT asks to view events, titles, times and attendees. It does not use calendar access to start recording.",
  },
  {
    id: "zoom",
    question: "Does WIT require Zoom?",
    answer:
      "No. Connecting Zoom is optional and only needed to capture Zoom meetings. If you never join Zoom meetings, you can skip it during setup.",
  },
  {
    id: "private",
    question: "Can I keep meeting notes private?",
    answer:
      "Yes. Meetings are private by default, and the sharing state is always visible on every meeting: Private, Shared with attendees, or Shared with team.",
  },
  {
    id: "share",
    question: "Can I share notes with attendees?",
    answer:
      "Yes. You choose per meeting, and you can set a default during setup. Sharing a meeting with a link is only offered when your workspace allows it.",
  },
  {
    id: "search",
    question: "Can I search old meetings?",
    answer:
      "Yes. Search covers meeting titles, participants, transcripts, action items, decisions and deals, and each result jumps to the moment in the conversation.",
  },
  {
    id: "ask",
    question: "Can I ask questions about a meeting?",
    answer:
      "Yes. Ask about a single meeting and WIT answers with links to the moments it used. In this demo the answers are pre-written, not generated by a live model.",
  },
  {
    id: "export",
    question: "Can I export my notes?",
    answer:
      "You can copy any follow-up email today. File exports are not part of this demo build yet.",
  },
  {
    id: "edit-actions",
    question: "Can I edit AI-generated action items?",
    answer:
      "Yes. You can change an action item’s title, owner and due date, mark it complete, or dismiss it. Each one keeps its link to the original conversation.",
  },
  {
    id: "transcription-fails",
    question: "What happens if transcription fails?",
    answer:
      "The meeting is marked as failed, your recording is kept, and you are told in Alerts. You can retry processing from the meeting without losing anything.",
  },
]
