import type { MeetingSpec } from "./spec"

export const clientDiscovery: MeetingSpec = {
  slug: "client_discovery",
  title: "Client Discovery",
  day: -1,
  time: "15:00",
  durationSec: 2160,
  status: "ready",
  visibility: "attendees",
  platform: "zoom",
  captureMode: "video",
  owner: "waleed",
  participants: [["waleed"], ["ali"], ["usman"]],
  tags: ["client", "sales", "pricing"],
  dealId: "deal_meridian_freight",
  sharedWithMe: false,
  lines: [
    ["ali", "00:05", "Thanks for making time, Usman. Last time we talked about how your dispatch team handles customer calls. Today I'd like to look at what that would mean for Meridian in practice."],
    ["usman", "00:28", "Sure. For context, I sign off on operations tooling, so anything we choose goes through me and then to finance."],
    ["waleed", "00:52", "That helps. Waleed here from our side. I'll cover the technical parts, mainly how capture works and how data leaves our system."],
    ["usman", "01:15", "Good. Our biggest problem is that dispatchers promise things on the phone, like a pickup window or a rate adjustment, and nobody writes it down."],
    ["ali", "01:48", "And then a customer calls back and asks what was agreed."],
    ["usman", "02:05", "Exactly. And then we argue about it. If your tool can show us what was actually said, that alone is valuable."],
    ["ali", "02:22", "Great. I sent the proposal on Monday, so let's talk about where it landed."],
    ["usman", "02:31", "We need to understand the pricing before moving forward."],
    ["ali", "02:50", "Of course. The proposal covers 120 dispatcher seats at $24,800 for the first year, including onboarding and the calendar integration."],
    ["usman", "03:20", "Right. Let me be honest about where I am with that."],
    ["usman", "03:41", "My concern is that the number is well above what we budgeted. Finance was expecting something closer to eighteen thousand."],
    ["ali", "04:12", "I understand. Can I ask whether the 120 seats are all active dispatchers, or is that the total headcount?"],
    ["usman", "04:40", "Total headcount. In practice about seventy people are on the phones in a given week."],
    ["waleed", "05:10", "Then a phased rollout could work. Start with the seventy active dispatchers and add seats as other teams adopt it."],
    ["ali", "05:40", "That would change the numbers meaningfully. Waleed and I can put together a revised proposal that prices the first phase separately."],
    ["usman", "06:10", "I'd like that. A smaller first phase is much easier to approve than the full number."],
    ["usman", "07:00", "The other thing finance will ask is where recordings are stored and who can access them."],
    ["waleed", "07:30", "Recordings are private to the person who captured them by default. Sharing is an explicit choice, and capture is always started manually by the user."],
    ["usman", "08:05", "That matters. My dispatchers would not accept something that records every call automatically."],
    ["waleed", "08:30", "It doesn't. Connecting a calendar gives us context only. Nothing is captured unless someone starts it."],
    ["usman", "09:10", "Good. Can recordings stay within our region? Our contracts with some customers require it."],
    ["waleed", "09:40", "I don't want to guess. I'll confirm what we can offer on data location and send it in writing."],
    ["ali", "10:30", "What's your timeline? When would you want the first dispatchers using it?"],
    ["usman", "11:00", "Ideally before the end of the quarter, which means I need a decision from finance within the next two weeks."],
    ["ali", "12:20", "Then let's aim to have the revised proposal in your inbox tomorrow, so finance has time to review it."],
    ["waleed", "12:50", "I'll send it. I'll include the phased pricing and a short security overview."],
    ["usman", "13:30", "Perfect. If the first phase fits the budget, I think we can move quickly."],
    ["ali", "14:20", "Before we close on the commercial side, I'd like to understand how your team would roll this out. Who would lead it on your side?"],
    ["usman", "15:10", "Probably me and one shift supervisor. We'd start with the morning dispatch team because they handle most of the contract customers."],
    ["waleed", "16:00", "That works well. A small group lets us learn what your calls look like, and we can adjust the summary settings for freight terminology."],
    ["usman", "17:20", "What does the setup involve? I don't want my team to spend a week in training."],
    ["waleed", "18:05", "About an hour. Each person connects their calendar, picks a sharing default, and learns how to start and stop capture."],
    ["usman", "19:30", "And if a call is sensitive, can the dispatcher keep it private?"],
    ["waleed", "20:00", "Yes. Meetings are private unless the person chooses to share them, and you can set the default to only me."],
    ["ali", "22:40", "Let me also ask about integrations. Do you use a CRM, or is dispatch work tracked somewhere else?"],
    ["usman", "23:20", "A dispatch system we built years ago. Nothing that has an API we'd want to expose, so we'll copy notes manually at first."],
    ["waleed", "24:10", "That's fine for phase one. Exports are available, and we can look at an integration later if it proves useful."],
    ["usman", "27:30", "Okay. I think I have what I need to go back to finance. The phased approach is the part that makes this feasible."],
    ["ali", "29:40", "Then to recap, Waleed sends the revised proposal tomorrow, I'll send the invite, and we meet on Friday the ninth."],
    ["usman", "30:20", "Yes. Let's do Friday the ninth, in the afternoon."],
    ["ali", "31:00", "Perfect. I'll send an invite. Thanks, Usman."],
  ],
  insights: {
    overview:
      "Usman Raza, who signs off on operations tooling at Meridian Freight, wants dispatcher promises to be traceable but said the proposal is well above budget. The team agreed to price a smaller first phase for roughly 70 active dispatchers and send a revised proposal tomorrow, together with a security overview. Data location for recordings is an open question.",
    keyPoints: [
      "Meridian wants to stop disputes over what dispatchers promised on calls.",
      "The proposal of $24,800 for 120 seats is above the budget finance expected.",
      "About 70 of the 120 dispatchers are on the phones in a given week.",
      "Manual capture is a requirement for Meridian's dispatchers.",
      "Finance needs a decision within two weeks.",
    ],
    decisions: [
      {
        at: "05:40",
        title: "Prepare a revised proposal with a separately priced first phase",
        context: "Phase one covers the roughly 70 active dispatchers, with seats added as other teams adopt it.",
        by: "ali",
      },
      {
        at: "30:20",
        title: "Walkthrough with finance set for Friday, October 9",
        by: "usman",
      },
    ],
    actions: [
      {
        at: "12:50",
        title: "Send revised proposal",
        description: "Include phased pricing for the first 70 seats and a short security overview.",
        who: "waleed",
        due: 1,
        status: "open",
      },
      {
        at: "09:40",
        title: "Confirm data location options for recordings",
        who: "waleed",
        due: 3,
        status: "open",
      },
      {
        at: "31:00",
        title: "Send invite for finance walkthrough",
        who: "ali",
        due: 1,
        status: "open",
      },
    ],
    questions: [
      {
        at: "09:10",
        text: "Can recordings stay within Meridian's region?",
        by: "usman",
        status: "open",
      },
      {
        at: "10:30",
        text: "When do the first dispatchers need to be using it?",
        by: "ali",
        status: "answered",
        answer: "Ideally before the end of the quarter, with a finance decision within two weeks.",
      },
    ],
    risks: [
      {
        at: "03:41",
        title: "Price is well above Meridian's budget",
        description: "Finance expected about $18,000 against the proposed $24,800.",
        severity: "high",
        by: "usman",
      },
      {
        at: "07:00",
        title: "Finance security review could delay signature",
        severity: "medium",
        by: "usman",
      },
    ],
    moments: [
      { at: "02:31", type: "question", title: "Meridian wants to understand the pricing", description: "We need to understand the pricing before moving forward." },
      { at: "03:41", type: "risk", title: "Customer objection: price above budget", rel: "r1" },
      { at: "05:40", type: "decision", title: "Phased first-phase pricing", rel: "d1" },
      { at: "08:05", type: "insight", title: "Dispatchers would reject automatic recording" },
      { at: "12:50", type: "commitment", title: "Waleed will send the revised proposal tomorrow", rel: "a1" },
    ],
    topics: [
      { label: "Dispatcher promises", from: "00:28", to: "02:22" },
      { label: "Pricing", from: "02:22", to: "06:10" },
      { label: "Security and data location", from: "07:00", to: "10:30" },
      { label: "Rollout and integrations", from: "14:20", to: "27:30" },
      { label: "Timeline and next steps", from: "27:30", to: "31:00" },
    ],
  },
}
