import type { MeetingSpec } from "./spec"

export const customerResearch: MeetingSpec = {
  slug: "customer_research",
  title: "Customer Research",
  day: -7,
  time: "13:00",
  durationSec: 2820,
  status: "ready",
  visibility: "team",
  platform: "zoom",
  captureMode: "video",
  owner: "ayesha",
  participants: [["ayesha"], ["waleed"], ["bilal"]],
  tags: ["research", "client"],
  dealId: "deal_atlas_properties",
  sharedWithMe: true,
  lines: [
    ["ayesha", "00:10", "Thanks, Bilal. I'm Ayesha, I lead product here. This isn't a sales call. I just want to understand how your team handles meetings today, and there are no wrong answers."],
    ["bilal", "00:40", "Happy to help. We manage about forty residential buildings, so a lot of my week is calls with owners, contractors and tenants' associations."],
    ["ayesha", "01:20", "Tell me about the last one that went badly. What happened?"],
    ["bilal", "01:45", "A contractor claimed we'd approved extra work on a roof repair. Nobody could find the email, and I couldn't remember what I said on the call."],
    ["ayesha", "02:30", "So how did you resolve it?"],
    ["bilal", "02:50", "We paid. It was cheaper than arguing. But it was about a thousand dollars we didn't need to spend."],
    ["waleed", "03:40", "Do you take notes during these calls, or does someone else?"],
    ["bilal", "04:05", "I take notes in a notebook. My assistant types them up when she has time, which is usually never."],
    ["ayesha", "05:30", "If you had a perfect record of that call, what would you want out of it?"],
    ["bilal", "06:10", "Honestly, I wouldn't read it. I'd want to search for a name or a phrase and land on the exact moment."],
    ["waleed", "07:20", "That's helpful. Would you want it to produce a summary as well?"],
    ["bilal", "07:50", "A short one, yes. Mostly who agreed to what, and by when."],
    ["ayesha", "09:30", "Let's talk about who else sees these notes. Do you share them?"],
    ["bilal", "10:05", "With my team, sometimes. With owners, never. I don't want them to see everything that was said."],
    ["ayesha", "11:15", "So you'd want control over what gets shared."],
    ["bilal", "11:45", "Yes, and it should be private by default. I've used tools where everything is shared and I always forget to turn it off."],
    ["waleed", "13:00", "And how do you feel about a tool joining your calls and recording automatically?"],
    ["bilal", "13:30", "I wouldn't use it. Half of my calls are with people who haven't agreed to be recorded. I need to be the one who decides."],
    ["ayesha", "15:10", "That's very clear. What about follow-ups after a call? What do you send?"],
    ["bilal", "15:40", "A short email, usually the same evening. It lists what we agreed and what each person will do."],
    ["ayesha", "17:20", "How long does that take you?"],
    ["bilal", "17:45", "Twenty minutes if I remember everything, an hour if I don't. And I often don't."],
    ["waleed", "19:30", "What if that email were drafted for you from the call?"],
    ["bilal", "20:00", "I'd still edit it. But a draft with the right items in it would save me most of the work."],
    ["bilal", "21:05", "Honestly the thing I need isn't the transcript. It's knowing which promises we made to tenants so I can chase them before they chase me."],
    ["ayesha", "21:50", "Say more about that. How do you track those promises today?"],
    ["bilal", "22:20", "I don't, really. They live in my head, or in a notebook. When a tenant calls to ask where their repair is, I'm already behind."],
    ["ayesha", "24:00", "If you had a list of commitments across all your calls, how would you use it?"],
    ["bilal", "24:40", "I'd check it every morning. Overdue items first, then anything due this week."],
    ["waleed", "26:15", "Would you want the list grouped by building or by person?"],
    ["bilal", "26:45", "By building. That's how my team thinks about the work."],
    ["ayesha", "29:30", "Let's talk about what makes you trust a summary. What would make you doubt it?"],
    ["bilal", "30:10", "If I can't see where it came from. If it says the contractor agreed to Friday, I want to hear him say it."],
    ["ayesha", "31:45", "That's a theme we've heard a lot. Being able to jump to the source."],
    ["bilal", "32:20", "Exactly. Otherwise I'd have to listen to the whole call, and then what's the point?"],
    ["waleed", "34:10", "What would make you stop using a tool like this?"],
    ["bilal", "34:50", "If it got things wrong without telling me. Or if setting it up took more than an afternoon."],
    ["ayesha", "37:00", "That's fair. We keep setup short on purpose. Is there anything I haven't asked that I should have?"],
    ["bilal", "38:10", "Pricing, perhaps. We're a small business, and per-seat pricing adds up quickly for people who only join calls occasionally."],
    ["ayesha", "39:20", "That's useful. I'll pass it to the team."],
    ["bilal", "41:00", "Thank you. This was more useful for me than I expected."],
    ["ayesha", "42:30", "Thank you, Bilal. I'll send you a summary of what we heard."],
  ],
  insights: {
    overview:
      "Bilal Qureshi from Atlas Properties manages about forty residential buildings and loses money when verbal agreements cannot be proven. His priority is tracking promises made to tenants and contractors, not reading transcripts. He wants private-by-default notes, manual control over recording, and summaries that link back to the exact moment in the call.",
    keyPoints: [
      "A forgotten verbal approval cost Atlas about a thousand dollars.",
      "He wants to search for a phrase and land on the exact moment, not read transcripts.",
      "Tracking commitments made to tenants is the highest-value feature for him.",
      "He would not use a tool that records automatically.",
      "Summaries must show their source, or he will not trust them.",
    ],
    decisions: [
      {
        at: "39:20",
        title: "Evaluate per-seat pricing for occasional participants",
        context: "Small businesses may have many people who only join calls occasionally.",
        by: "ayesha",
      },
    ],
    actions: [
      {
        at: "42:30",
        title: "Send Bilal a summary of what we heard",
        who: "ayesha",
        due: 1,
        status: "open",
      },
      {
        at: "21:50",
        title: "Prototype a commitments view grouped by building",
        who: "waleed",
        status: "open",
      },
      {
        at: "39:20",
        title: "Share pricing feedback with the product team",
        who: "ayesha",
        due: -4,
        status: "completed",
      },
    ],
    questions: [
      {
        at: "24:00",
        text: "How would a cross-meeting commitments list be used day to day?",
        by: "ayesha",
        status: "answered",
        answer: "He would check it every morning, overdue items first, grouped by building.",
      },
    ],
    risks: [
      {
        at: "34:50",
        title: "Wrong output without a source would end adoption",
        description: "If the tool gets things wrong without telling the user, or takes more than an afternoon to set up, he would stop using it.",
        severity: "medium",
        by: "bilal",
      },
    ],
    moments: [
      { at: "01:45", type: "insight", title: "A forgotten verbal approval cost about a thousand dollars" },
      { at: "13:30", type: "risk", title: "Automatic recording is a deal-breaker" },
      { at: "21:05", type: "insight", title: "Product insight: track promises made to tenants, not transcripts" },
      { at: "30:10", type: "insight", title: "Summaries need a visible source to be trusted" },
      { at: "38:10", type: "question", title: "Per-seat pricing may not suit occasional participants" },
    ],
    topics: [
      { label: "Background and last bad call", from: "00:10", to: "05:30" },
      { label: "What a perfect record looks like", from: "05:30", to: "13:00" },
      { label: "Recording and consent", from: "13:00", to: "15:10" },
      { label: "Follow-ups and commitments", from: "15:10", to: "29:30" },
      { label: "Trust and pricing", from: "29:30", to: "42:30" },
    ],
  },
}
