import type { MeetingSpec } from "./spec"

export const engineeringSync: MeetingSpec = {
  slug: "eng_sync",
  title: "Engineering Sync",
  day: -1,
  time: "10:00",
  durationSec: 1680,
  status: "ready",
  visibility: "team",
  platform: "google_meet",
  captureMode: "audio",
  owner: "ahmed",
  participants: [["ahmed"], ["waleed"], ["hamza"], ["sara"]],
  tags: ["engineering", "launch"],
  sharedWithMe: true,
  lines: [
    ["ahmed", "00:06", "Let's keep this under thirty minutes. Three topics: the deployment plan for the new API, the flaky tests, and on-call for launch week."],
    ["hamza", "00:28", "Starting with deployment. My proposal is to ship the new endpoints behind a feature flag, so we can turn them on for the beta cohort without redeploying."],
    ["waleed", "01:05", "I like that. It also gives us an instant rollback if the dashboard misbehaves, which is what I'm most worried about."],
    ["ahmed", "01:40", "Any objection to one flag per environment? Staging first, then production for internal users, then the beta."],
    ["sara", "02:05", "No objection from design. Can the new dashboard share the flag? I'd like to test loading states with real data."],
    ["hamza", "02:35", "Yes, they can share one flag. I'll name it so it's obvious what it controls."],
    ["ahmed", "03:05", "Good. Decision then: the new API goes out behind a feature flag, with a staged rollout through internal users and then the beta."],
    ["ahmed", "03:50", "Separate item. The platform team shared their deployment plan for the auth changes. Waleed, can you review it when you get a chance? There's no deadline, I just want a second pair of eyes."],
    ["waleed", "04:30", "Sure. I'll read it this week and leave comments."],
    ["hamza", "05:10", "While we're on auth, the token refresh is the piece we're blocked on. Their release date isn't confirmed."],
    ["ahmed", "05:45", "I know. I'm chasing it. For now, assume it's not ready before Tuesday."],
    ["waleed", "06:30", "I can stub it locally so we aren't blocked, but we shouldn't ship against a stub."],
    ["ahmed", "07:00", "Agreed. Nothing ships against a stub."],
    ["hamza", "08:20", "Moving to flaky tests. We have six tests in the capture flow that fail about one run in ten."],
    ["sara", "09:00", "Waleed, is that the timer test? I saw it fail on your branch twice."],
    ["hamza", "09:25", "Yes, the timer test and the pause and resume tests. They depend on real time, which is the problem."],
    ["waleed", "10:10", "We should use fake timers. I fixed the same pattern in the upload tests last month, so I can show Hamza."],
    ["ahmed", "10:50", "Good. Hamza, please make that a priority. Flaky tests get ignored, and then real failures hide behind them."],
    ["hamza", "12:10", "I'll start tomorrow."],
    ["ahmed", "13:00", "On-call for launch week. Who is willing to take it, and for how long?"],
    ["waleed", "13:40", "I can take the first two days. After that someone else should rotate in."],
    ["hamza", "14:20", "I'll take the next two days. I'd rather not do the weekend, though."],
    ["ahmed", "14:55", "Nobody does the weekend if we've done the job properly. Let's leave Friday open for now."],
    ["sara", "16:30", "Is there anything design should watch during launch? I could join the first day to catch visual bugs."],
    ["ahmed", "17:05", "That would help. Please post what you find in the launch channel as you see it."],
    ["hamza", "18:20", "One more risk. Staging has about a tenth of the production data, so performance numbers there can mislead us."],
    ["waleed", "19:10", "Let's run one test against a production-sized snapshot before the beta."],
    ["ahmed", "19:50", "Add it to the plan. Waleed, can you own it?"],
    ["waleed", "20:10", "Yes, I'll own it and report numbers before the beta invites go out."],
    ["hamza", "22:10", "Last thing from me. The meetings list fetches everything on load. I'd like to paginate it before we invite users."],
    ["ahmed", "23:30", "Agreed, and it fits with the cursor pagination in the new API. Anything else?"],
    ["sara", "25:00", "Nothing from me."],
    ["ahmed", "26:40", "Then we're done. Thanks, everyone."],
  ],
  insights: {
    overview:
      "The team agreed to ship the new API behind a feature flag with a staged rollout. The auth token refresh release is still unconfirmed and is blocking final integration. Flaky capture-flow tests will be fixed with fake timers, and launch-week on-call is partly covered, with Friday still open.",
    keyPoints: [
      "The new API ships behind a single feature flag shared with the new dashboard.",
      "The auth token refresh release date is unconfirmed. Assume it is not ready before Tuesday.",
      "Six capture-flow tests fail intermittently because they depend on real time.",
      "Staging holds about a tenth of production data, so a production-sized test is needed.",
    ],
    decisions: [
      {
        at: "03:05",
        title: "Ship the new API behind a feature flag with a staged rollout",
        context: "Staging first, then production for internal users, then the beta cohort.",
        by: "ahmed",
      },
      {
        at: "07:00",
        title: "Nothing ships against a stubbed token refresh",
        context: "A local stub is acceptable for development only.",
        by: "ahmed",
      },
    ],
    actions: [
      {
        at: "03:50",
        title: "Review deployment plan",
        description: "Review the platform team's deployment plan for the auth changes and leave comments.",
        who: "waleed",
        status: "open",
      },
      {
        at: "10:50",
        title: "Replace real timers with fake timers in capture-flow tests",
        who: "hamza",
        due: 5,
        status: "in_progress",
      },
      {
        at: "20:10",
        title: "Run a performance test on a production-sized snapshot",
        who: "waleed",
        due: 7,
        status: "open",
      },
      {
        at: "22:10",
        title: "Paginate the meetings list",
        who: "hamza",
        due: 6,
        status: "open",
      },
    ],
    questions: [
      {
        at: "14:55",
        text: "Who covers on-call on Friday of launch week?",
        by: "ahmed",
        status: "open",
      },
    ],
    risks: [
      {
        at: "05:10",
        title: "Token refresh release date is unconfirmed",
        description: "Final integration is blocked until the auth service ships the new token refresh.",
        severity: "high",
        by: "hamza",
      },
      {
        at: "18:20",
        title: "Staging data is a tenth of production",
        description: "Performance results in staging may not reflect production behavior.",
        severity: "medium",
        by: "hamza",
      },
    ],
    moments: [
      { at: "03:05", type: "decision", title: "New API behind a feature flag", rel: "d1" },
      { at: "05:10", type: "risk", title: "Token refresh release unconfirmed", rel: "r1" },
      { at: "09:25", type: "insight", title: "Flaky tests depend on real time" },
      { at: "14:55", type: "question", title: "Friday on-call is still uncovered", rel: "q1" },
      { at: "20:10", type: "commitment", title: "Waleed owns the production-sized performance test", rel: "a3" },
    ],
    topics: [
      { label: "Deployment plan", from: "00:06", to: "07:00" },
      { label: "Flaky tests", from: "08:20", to: "12:10" },
      { label: "Launch-week on-call", from: "13:00", to: "17:05" },
      { label: "Performance and pagination", from: "18:20", to: "23:30" },
    ],
  },
}
