import type { MeetingSpec } from "./spec"

export const leadershipSync: MeetingSpec = {
  slug: "leadership_sync",
  title: "Leadership Sync",
  day: -1,
  time: "16:30",
  durationSec: 2400,
  status: "ready",
  visibility: "team",
  platform: "microsoft_teams",
  captureMode: "audio",
  owner: "ahmed",
  participants: [["ahmed"], ["ayesha"], ["ali"], ["waleed"]],
  tags: ["leadership", "sales", "pricing"],
  dealId: "deal_vertex_digital",
  sharedWithMe: true,
  lines: [
    ["ahmed", "00:10", "Let's use the next forty minutes for three things: the pipeline, the launch, and hiring. Ali, you're first."],
    ["ali", "00:35", "Pipeline is in better shape than it looks. Atlas Properties signed at $31,200 on Monday, which is our first closed deal this quarter."],
    ["ahmed", "01:05", "Good news. And Crescent Health?"],
    ["ali", "01:20", "We lost them. They went with a competitor that bundled a clinical scheduling tool, and the $22,000 we quoted wasn't the deciding factor."],
    ["ayesha", "02:00", "Do we know what they actually valued? I'd like to understand if it's a product gap."],
    ["ali", "02:25", "Maryam said they wanted one vendor for scheduling and notes. That's a bundle problem, not a quality problem."],
    ["ahmed", "03:10", "Noted. We don't need to chase that. Vertex Digital next."],
    ["ali", "03:40", "Vertex is in negotiation at $40,000. Hira's team wants a 12-month term and has asked for a ten percent discount."],
    ["waleed", "04:20", "Is there anything on the technical side that's blocking? They asked about SSO last time."],
    ["ali", "04:50", "SSO is the sticking point, but they're willing to sign if it's on the roadmap with a date."],
    ["ahmed", "05:40", "I don't want to promise a date we can't hold. What can we say honestly?"],
    ["waleed", "06:10", "That it's planned for the quarter after launch. I wouldn't give a day."],
    ["ayesha", "06:50", "I agree. A discount doesn't solve their SSO concern anyway."],
    ["ahmed", "08:00", "Then here's my position. We hold the price at $40,000 and offer quarterly billing instead of a discount."],
    ["ali", "08:30", "That works. I think quarterly billing helps their finance team more than ten percent would."],
    ["ahmed", "09:00", "Good. Let's make that the offer."],
    ["ali", "09:30", "I'll send Vertex the revised terms after this call, by Tuesday at the latest."],
    ["ayesha", "11:40", "Moving to the launch. We settle the date in product planning tomorrow morning, and my expectation is that it lands in mid-October."],
    ["ahmed", "12:30", "I'd rather hear the final date after that meeting. Ayesha, can you send a note when it's confirmed?"],
    ["ayesha", "13:00", "Yes, I'll send it to this group once the notes are confirmed."],
    ["ahmed", "15:20", "Now hiring. We need to decide whether the next hire is a second backend engineer or a customer success manager."],
    ["waleed", "16:10", "From engineering, a second backend engineer would take pressure off the API work, but I understand customers need support."],
    ["ali", "17:00", "Sales needs the other one. When a deal closes, there's nobody to run the kickoff. I've been doing it myself."],
    ["ayesha", "18:20", "I agree, and the beta will need someone for that too."],
    ["ahmed", "19:30", "Then the first hire is a customer success manager. We'll post the role this week."],
    ["ahmed", "21:00", "Ayesha, can you write the job description?"],
    ["ayesha", "21:25", "Yes, I'll draft it by Friday."],
    ["ahmed", "24:10", "Any risks I should know about before we close?"],
    ["ali", "24:40", "The Meridian proposal is above their budget. I think we can fix it with phasing, but it needs attention this week."],
    ["ahmed", "25:30", "Okay. Keep me updated. Thanks, everyone."],
  ],
  insights: {
    overview:
      "Leadership reviewed the pipeline: Atlas Properties closed at $31,200 and Crescent Health was lost to a bundled competitor. For Vertex Digital the team decided to hold the $40,000 price and offer quarterly billing in place of a discount. The first new hire will be a customer success manager.",
    keyPoints: [
      "Atlas Properties signed at $31,200, the first closed deal this quarter.",
      "Crescent Health chose a competitor that bundled clinical scheduling.",
      "Vertex Digital's remaining concern is SSO, which is planned for the quarter after launch.",
      "The first hire will be a customer success manager.",
      "The Meridian Freight proposal is above budget and needs attention this week.",
    ],
    decisions: [
      {
        at: "08:00",
        title: "Hold Vertex Digital at $40,000 and offer quarterly billing",
        context: "A discount does not address their SSO concern. Quarterly billing helps their finance team.",
        by: "ahmed",
      },
      {
        at: "19:30",
        title: "The first hire is a customer success manager",
        context: "Nobody currently runs customer kickoffs after a deal closes, and the beta will need the role.",
        by: "ahmed",
      },
    ],
    actions: [
      {
        at: "09:30",
        title: "Send Vertex Digital the revised terms",
        who: "ali",
        due: 5,
        status: "open",
      },
      {
        at: "21:25",
        title: "Draft the customer success manager job description",
        who: "ayesha",
        due: 1,
        status: "open",
      },
      {
        at: "13:00",
        title: "Send the final launch date to leadership",
        who: "ayesha",
        due: 1,
        status: "open",
      },
    ],
    questions: [
      {
        at: "05:40",
        text: "What can we honestly say to Vertex about the SSO date?",
        by: "ahmed",
        status: "answered",
        answer: "It is planned for the quarter after launch, without a specific day.",
      },
    ],
    risks: [
      {
        at: "24:40",
        title: "Meridian Freight proposal is above budget",
        description: "A phased first-phase price may fix it, but it needs attention this week.",
        severity: "high",
        by: "ali",
      },
      {
        at: "04:50",
        title: "SSO is the sticking point for Vertex Digital",
        severity: "medium",
        by: "ali",
      },
    ],
    moments: [
      { at: "00:35", type: "insight", title: "Atlas Properties signed at $31,200" },
      { at: "01:20", type: "insight", title: "Crescent Health lost to a bundled competitor" },
      { at: "08:00", type: "decision", title: "Hold $40,000 and offer quarterly billing", rel: "d1" },
      { at: "19:30", type: "decision", title: "First hire: customer success manager", rel: "d2" },
      { at: "24:40", type: "risk", title: "Meridian proposal above budget", rel: "r1" },
    ],
    topics: [
      { label: "Pipeline review", from: "00:10", to: "11:40" },
      { label: "Launch", from: "11:40", to: "15:20" },
      { label: "Hiring", from: "15:20", to: "24:10" },
      { label: "Risks", from: "24:10", to: "25:30" },
    ],
  },
}
