import type { MeetingSpec } from "./spec"

export const productPlanningOct1: MeetingSpec = {
  slug: "pp_1001",
  title: "Product Planning",
  day: 0,
  time: "08:00",
  durationSec: 2520,
  status: "ready",
  visibility: "attendees",
  platform: "zoom",
  captureMode: "video",
  owner: "waleed",
  participants: [["waleed"], ["ayesha"], ["sara"], ["ahmed"], ["hamza"]],
  tags: ["planning", "launch", "beta"],
  sharedWithMe: false,
  lines: [
    ["ayesha", "00:08", "Okay, let's get started. We have about forty minutes, and the main thing I want out of this is a launch date we all believe in."],
    ["waleed", "00:24", "Right. Last week we said October 12. Since then the API work has taken longer than I estimated, and I would rather say that now than on the eleventh."],
    ["hamza", "00:44", "The new endpoints are all in staging. The problem is that the dashboard still calls the old API on two screens, the meetings list and the deal view."],
    ["ahmed", "01:02", "Those are the two highest-traffic screens, so we can't ship around them. How much time do you need to move them over?"],
    ["waleed", "01:12", "I think we should move the launch to next Friday."],
    ["hamza", "01:15", "Another week covers the migration and a full regression pass, so I'm comfortable with that."],
    ["ayesha", "01:20", "Sara, does a later date cause any trouble for the final screens?"],
    ["sara", "01:24", "That works from the design side."],
    ["ahmed", "01:30", "From engineering, I'd rather commit to one firm date than keep moving a soft one. What's the exact date?"],
    ["waleed", "01:38", "Okay, let's make October 15 the official target."],
    ["ayesha", "01:46", "Good. October 15 it is. I'll update the roadmap and let support know once we're done here."],
    ["hamza", "02:04", "One caveat. October 15 only holds if the API integration is finished and merged by the end of next week. That is the main dependency."],
    ["waleed", "02:28", "Agreed, and that's on me. The integration is the only thing between us and a stable build, so I'll treat it as the critical path."],
    ["sara", "02:50", "Does the new API change the response shape for the dashboard? I need to know if the empty and loading states I designed still apply."],
    ["hamza", "03:10", "Mostly no. Pagination moves to cursors, so a load more button replaces page numbers, but the fields you design around are the same."],
    ["sara", "03:34", "That's fine. Load more is what I mocked up anyway."],
    ["ayesha", "04:05", "Let's talk about the beta, because the date only matters if the right people are in it. I'd like to start small and learn quickly."],
    ["ahmed", "04:30", "How small? Support is two people right now, and they will be the ones answering questions."],
    ["ayesha", "04:52", "Fifty users. Mostly teams from the waitlist who already told us they run weekly customer calls."],
    ["hamza", "05:20", "Fifty is fine for infrastructure. We could handle ten times that, so the limit is really about how much feedback we can read."],
    ["waleed", "05:48", "I agree with fifty. If we hit real problems, we want to fix them before they reach hundreds of people."],
    ["ahmed", "06:20", "Fine by me, as long as onboarding is covered. Somebody has to walk those teams through connecting their calendars and what capture does."],
    ["ayesha", "06:50", "Good point. Let's park that and come back to it."],
    ["hamza", "07:05", "Speaking of dependencies, the integration also needs the new token refresh from the auth service."],
    ["waleed", "08:14", "That's the real risk. If auth slips past next Tuesday, the integration slips with it, and then so does October 15."],
    ["ahmed", "08:40", "I'll talk to the platform team today and get a written release date. If it's after Tuesday, we revisit this."],
    ["ayesha", "09:10", "Please do. I don't want to learn about it on the thirteenth."],
    ["waleed", "09:35", "Same. I'll add a check-in on Monday so we find out early if anything shifts."],
    ["hamza", "10:20", "While we wait, I can stub the token refresh locally so the dashboard work isn't blocked."],
    ["sara", "10:50", "That helps me too. I'd like to test the real loading states against actual responses, not mock ones."],
    ["ayesha", "11:30", "Okay. Can we talk about the dashboard itself? Are we shipping the beta on the new API, or running both in parallel?"],
    ["hamza", "12:05", "Running both doubles the testing surface. I'd say new API only, and we remove the old calls from those two screens."],
    ["ahmed", "12:25", "I agree. One code path is easier to support, and fifty beta users is a good size to find what we missed."],
    ["ayesha", "12:40", "Then that's decided. The new dashboard ships on the new API only."],
    ["waleed", "13:20", "I'll write up what changes for anyone still calling the old endpoints so nobody gets surprised."],
    ["sara", "14:10", "Quick design note. The beta banner and the feedback button are the last two pieces I owe. I'll hand them off by Monday."],
    ["ayesha", "15:00", "Thanks. Now the part I've been putting off, which is pricing. We said the beta would be free, but I want to confirm it out loud."],
    ["ahmed", "15:40", "My view is free for the beta, with a clear note that pricing comes later. Charging fifty early users adds friction and very little revenue."],
    ["waleed", "16:20", "It also keeps the conversation honest. We're asking for feedback, not selling a finished product."],
    ["hamza", "16:50", "And billing isn't built yet. Charging anyone would mean manual invoices."],
    ["ayesha", "17:22", "Then let's settle it. The beta is limited to fifty users, it's free, and we revisit pricing after launch."],
    ["ahmed", "17:42", "Works for me. I'd like us to define what revisit means, though. Maybe a review two weeks after launch."],
    ["ayesha", "18:10", "Good idea. I'll put a pricing review on the calendar for the week of October 26."],
    ["sara", "18:50", "Who are we telling about the beta? Just the waitlist, or do customers get early access too?"],
    ["ayesha", "19:20", "Waitlist first. Customers like Northstar and Meridian will hear from sales once we know the beta is stable."],
    ["waleed", "20:10", "For documentation, I'll write the beta guide covering setup, calendar connection, and what capture does and doesn't do."],
    ["sara", "20:45", "I can turn that into an in-app onboarding guide. People would rather read three short screens than one long document."],
    ["hamza", "21:30", "One thing on the engineering side. We should add rate limits to the new endpoints before the beta, in case an integration misbehaves."],
    ["ahmed", "22:10", "Yes. Hamza, can that fit in this sprint?"],
    ["hamza", "22:25", "It's about two days of work. I can fit it in."],
    ["ayesha", "23:10", "Great. Let's cover support readiness. Who answers beta questions in the first week?"],
    ["ahmed", "24:00", "Support is two people. I'd like engineering on a rotation in the first week, one person a day."],
    ["waleed", "24:50", "I'll take Monday and Tuesday. The rest of the team can split the remaining days."],
    ["hamza", "25:40", "I'm happy with Wednesday and Thursday."],
    ["ayesha", "26:30", "Perfect. I'll put the rota in the launch doc."],
    ["sara", "27:20", "Let me add accessibility. The new dashboard should be checked with a screen reader before we invite anyone."],
    ["ahmed", "28:05", "Agreed. Sara, can you run that? Hamza can help with anything that needs code changes."],
    ["sara", "28:40", "Yes. I'll do it next week once the loading states are final."],
    ["ayesha", "29:30", "Okay, we have a few minutes left. There's one thing I don't think we've answered, and it keeps coming up."],
    ["waleed", "30:10", "Customer onboarding?"],
    ["ayesha", "31:05", "Right. Who owns customer onboarding during the beta? Someone has to run the kickoff calls and follow up when a team gets stuck, and right now that person doesn't exist."],
    ["ahmed", "31:45", "It can't be engineering. We'll be buried in the integration."],
    ["sara", "32:15", "Design can help with the guide, but not the calls."],
    ["ayesha", "32:50", "I'll look at whether customer success can take it. Let's leave it open for now and I'll bring it to Leadership Sync next week."],
    ["hamza", "34:30", "One last technical thing. We should freeze the old endpoints, not delete them, until after launch."],
    ["waleed", "35:30", "Agreed. Delete them once the beta is stable."],
    ["ahmed", "36:40", "Okay. Can someone summarize the actions before we close?"],
    ["ayesha", "37:20", "Sure. Waleed finishes the API integration and writes the beta documentation. Sara writes the onboarding guide. I'll pull together the invite list for the fifty users."],
    ["sara", "38:30", "I'll have the onboarding guide ready by Thursday, once Waleed's documentation is in."],
    ["waleed", "39:12", "And I'll finish the API integration by Friday next week, so we have the weekend and Monday for regression."],
    ["waleed", "39:40", "The beta documentation will be ready Monday, so Sara has something to build the guide from."],
    ["ayesha", "40:10", "Thank you, everyone. October 15, fifty users, new API. Let's go."],
  ],
  insights: {
    overview:
      "The team moved the launch from October 12 to October 15, giving engineering one more week to finish the API integration. The beta will be limited to 50 users and free of charge, and the new dashboard will ship on the new API only. The integration depends on an unconfirmed auth service release, and customer onboarding for the beta still has no owner.",
    keyPoints: [
      "API integration remains the primary dependency for the October 15 launch.",
      "The beta will initially include 50 users from the waitlist.",
      "Customer onboarding still needs an owner.",
      "The auth service release window is unconfirmed. Ahmed will get a written date today.",
      "Engineering will cover first-week beta support on a one-person-per-day rotation.",
    ],
    decisions: [
      {
        at: "01:38",
        title: "Launch moved to October 15",
        context: "Moved from October 12 to give engineering one more week for the API migration and a regression pass.",
        by: "waleed",
        supersedes: "dec_pp_0925_1",
      },
      {
        at: "12:40",
        title: "New dashboard ships on the new API only",
        context: "Running the old and new APIs in parallel would double the testing surface. The old endpoints are frozen, not deleted.",
        by: "ayesha",
      },
      {
        at: "17:22",
        title: "Beta limited to 50 users and free of charge",
        context: "Billing is not built yet. Pricing will be reviewed in the week of October 26.",
        by: "ayesha",
      },
    ],
    actions: [
      {
        at: "39:12",
        title: "Finish API integration",
        description: "Move the meetings list and deal view to the new endpoints and merge them before the regression pass.",
        who: "waleed",
        due: 8,
        status: "in_progress",
      },
      {
        at: "39:40",
        title: "Prepare beta documentation",
        description: "Cover setup, calendar connection, and what capture does and does not do.",
        who: "waleed",
        due: 4,
        status: "open",
      },
      {
        at: "38:30",
        title: "Write beta onboarding guide",
        description: "Three short in-app screens built from the beta documentation.",
        who: "sara",
        due: 7,
        status: "open",
      },
      {
        at: "37:20",
        title: "Confirm invite list for the 50-user beta",
        who: "ayesha",
        due: 5,
        status: "open",
      },
    ],
    questions: [
      {
        at: "31:05",
        text: "Who owns customer onboarding during the beta?",
        by: "ayesha",
        status: "open",
      },
    ],
    risks: [
      {
        at: "08:14",
        title: "API integration depends on an unconfirmed auth service release",
        description: "If the auth service slips past next Tuesday, the integration and the October 15 launch slip with it.",
        severity: "high",
        by: "waleed",
      },
      {
        at: "21:30",
        title: "New endpoints have no rate limits yet",
        description: "A misbehaving integration could affect other beta users. Rate limits need about two days of work.",
        severity: "medium",
        by: "hamza",
      },
    ],
    moments: [
      { at: "01:38", type: "decision", title: "Launch moved to October 15", rel: "d1" },
      { at: "08:14", type: "risk", title: "Auth service release is unconfirmed", rel: "r1" },
      { at: "12:40", type: "decision", title: "Dashboard ships on the new API only", rel: "d2" },
      { at: "17:22", type: "decision", title: "Beta capped at 50 users, free of charge", rel: "d3" },
      { at: "31:05", type: "question", title: "Customer onboarding has no owner", rel: "q1" },
      { at: "39:12", type: "commitment", title: "Waleed commits to finishing the API integration", rel: "a1" },
    ],
    topics: [
      { label: "Launch date and dependencies", from: "00:08", to: "07:05" },
      { label: "Auth service risk", from: "07:05", to: "11:30" },
      { label: "Dashboard on the new API", from: "11:30", to: "15:00" },
      { label: "Beta pricing and size", from: "15:00", to: "19:20" },
      { label: "Documentation and support readiness", from: "19:20", to: "29:30" },
      { label: "Customer onboarding ownership", from: "29:30", to: "34:30" },
      { label: "Wrap-up and actions", from: "34:30", to: "40:10" },
    ],
  },
}
