import type { MeetingSpec } from "./spec"

export const productPlanningSep18: MeetingSpec = {
  slug: "pp_0918",
  title: "Product Planning",
  day: -13,
  time: "11:00",
  durationSec: 1500,
  status: "ready",
  visibility: "attendees",
  platform: "zoom",
  captureMode: "audio",
  owner: "waleed",
  participants: [["waleed"], ["ayesha"], ["sara"], ["ahmed"], ["hamza"]],
  tags: ["planning", "launch"],
  sharedWithMe: false,
  lines: [
    ["ayesha", "00:10", "Thanks for joining. This is our first planning meeting for the launch, so the goal is to leave with a date and a short list of what has to be true by then."],
    ["waleed", "00:48", "Based on where the new dashboard is today, I think October 5 is achievable. It's tight, but the API changes are small."],
    ["hamza", "01:30", "They look small on paper. I haven't started the deal view yet, but I don't expect big surprises."],
    ["ahmed", "02:12", "I'd call October 5 optimistic, but there's no point padding before we know more. Let's set it and review progress in a week."],
    ["sara", "02:58", "Design is mostly done. Empty states and the beta banner are the only things left, and I can finish those in about a week."],
    ["ayesha", "03:40", "Okay. Is everyone comfortable with October 5 as the target?"],
    ["waleed", "04:02", "Yes. Let's lock October 5 as the launch date and review next Friday."],
    ["ayesha", "05:20", "Good. Next, what has to be true on launch day? I'll write the list as we go."],
    ["hamza", "06:05", "The dashboard on the new API, the capture flow stable, and the processing pipeline handling longer meetings."],
    ["waleed", "07:30", "Add calendar connection. It has to work with Google Calendar from day one."],
    ["sara", "08:25", "And onboarding. People need to understand that connecting a calendar doesn't start any recording."],
    ["ayesha", "09:10", "That's a big one for trust. I'll make it a launch requirement."],
    ["ahmed", "11:02", "Are we doing a beta first, or launching to everyone at once?"],
    ["ayesha", "11:40", "I'd like a small beta, but I haven't decided on a size yet. Let's talk about it next week."],
    ["hamza", "13:20", "One risk I want on the record. We haven't tested the processing pipeline with meetings longer than an hour."],
    ["waleed", "14:05", "I'll run a load test with long recordings this week and report back on Friday."],
    ["ahmed", "15:10", "Good. How long do the longest recordings take to process today?"],
    ["hamza", "16:30", "Around eleven minutes for a ninety-minute call, but that's on a quiet staging environment."],
    ["sara", "17:45", "I'll send the updated empty states by Wednesday so engineering can start wiring them."],
    ["ayesha", "19:20", "Great. Does anyone have anything else before we wrap up?"],
    ["ahmed", "21:00", "No. Let's meet again next Friday, same time."],
    ["ayesha", "22:40", "Perfect. I'll send the notes around this afternoon. Thanks, everyone."],
  ],
  insights: {
    overview:
      "The team set October 5 as the launch date for the new dashboard and agreed on what must be true by then: the dashboard on the new API, a stable capture flow, longer-meeting support in the processing pipeline, Google Calendar connection and clear onboarding about manual capture. A beta before launch was proposed but not sized.",
    keyPoints: [
      "Launch date set to October 5, with a progress review next Friday.",
      "Calendar connection and clear onboarding about manual capture are launch requirements.",
      "The processing pipeline has not been tested with meetings longer than an hour.",
      "A small beta is preferred, but its size is undecided.",
    ],
    decisions: [
      {
        at: "04:02",
        title: "Launch set for October 5",
        context: "Tight but achievable according to engineering. To be reviewed at next Friday's planning meeting.",
        by: "waleed",
      },
    ],
    actions: [
      {
        at: "14:05",
        title: "Run a load test with long recordings",
        description: "Test the processing pipeline with meetings longer than an hour and report back.",
        who: "waleed",
        due: -6,
        status: "completed",
      },
      {
        at: "17:45",
        title: "Send updated empty states",
        who: "sara",
        due: -8,
        status: "completed",
      },
    ],
    questions: [
      {
        at: "11:02",
        text: "Should there be a beta before the general launch, and how large?",
        by: "ahmed",
        status: "open",
      },
    ],
    risks: [
      {
        at: "13:20",
        title: "Pipeline untested with meetings longer than an hour",
        description: "Processing time for long recordings is unknown.",
        severity: "medium",
        by: "hamza",
      },
    ],
    moments: [
      { at: "04:02", type: "decision", title: "Launch set for October 5", rel: "d1" },
      { at: "08:25", type: "insight", title: "Onboarding must explain that connecting a calendar does not record" },
      { at: "13:20", type: "risk", title: "Long recordings are untested", rel: "r1" },
      { at: "14:05", type: "commitment", title: "Waleed will run a long-recording load test", rel: "a1" },
    ],
    topics: [
      { label: "Launch date", from: "00:10", to: "05:20" },
      { label: "Launch requirements", from: "05:20", to: "11:00" },
      { label: "Beta and risks", from: "11:02", to: "17:45" },
      { label: "Wrap-up", from: "17:45", to: "22:40" },
    ],
  },
}
