import type { MeetingSpec } from "./spec"

export const productPlanningSep25: MeetingSpec = {
  slug: "pp_0925",
  title: "Product Planning",
  day: -6,
  time: "11:00",
  durationSec: 1680,
  status: "ready",
  visibility: "attendees",
  platform: "zoom",
  captureMode: "audio",
  owner: "waleed",
  participants: [["waleed"], ["ayesha"], ["sara"], ["ahmed"], ["hamza"]],
  tags: ["planning", "launch"],
  sharedWithMe: false,
  lines: [
    ["ayesha", "00:08", "Quick recap before we start. We set October 5 last Friday. Hamza, where are we on the API work?"],
    ["hamza", "00:34", "Honestly, behind. The deal view needs a bigger change than I expected, and Waleed's load test turned something up."],
    ["waleed", "01:10", "Processing time grows faster than linearly for meetings over seventy-five minutes. I think we can fix it, but not by next Monday."],
    ["ahmed", "01:55", "So October 5 is off the table?"],
    ["waleed", "02:12", "I think so. Realistically we need another week, which makes it October 12."],
    ["sara", "02:50", "Does a week change anything for design? I finished the empty states on Wednesday."],
    ["ayesha", "03:15", "Not really. Let's confirm it out loud. Are we moving the launch to October 12?"],
    ["ahmed", "03:40", "I'm fine with October 12 if we agree it's firm. Another slip would hurt the team's credibility."],
    ["waleed", "04:08", "Agreed. Let's make October 12 the new launch date."],
    ["hamza", "05:00", "Then my priority is the processing fix, because the dashboard work depends on it."],
    ["ayesha", "06:20", "While we're here, I'd like to talk about the beta. I'm leaning toward a small group, but I don't have a number yet."],
    ["ahmed", "07:05", "What would the beta cost us in support time? We're a small team."],
    ["ayesha", "07:45", "That's what I want to find out. I'll come back next week with a proposal for size and who we invite."],
    ["sara", "09:30", "Whatever the size, I'd like the beta banner and a feedback button ready. I'll send designs this week."],
    ["waleed", "10:40", "Good. Can we also decide what happens to the old endpoints? I'd like to know if we maintain both."],
    ["hamza", "11:15", "I'd rather not. Maintaining two APIs through the beta doubles the testing."],
    ["ahmed", "12:05", "Let's not decide that today. Bring options next week."],
    ["ayesha", "13:30", "Fine. Hamza, can you give me a risk list for the processing fix by Wednesday?"],
    ["hamza", "14:10", "Yes, I'll write it up with a worst case and a best case."],
    ["waleed", "16:20", "I'll own the fix for long recordings and have it merged by Wednesday."],
    ["ahmed", "18:05", "Great. Anything else? If not, let's wrap early."],
    ["sara", "19:40", "Nothing from me. Thanks, everyone."],
  ],
  insights: {
    overview:
      "A load test showed processing time grows faster than linearly for meetings over 75 minutes, so October 5 was no longer realistic. The team moved the launch to October 12 and agreed to treat it as firm. A small beta is still under consideration, and the future of the old endpoints was deferred to next week.",
    keyPoints: [
      "Launch moved from October 5 to October 12 because of long-recording processing time.",
      "The new date is treated as firm. Another slip would hurt credibility.",
      "Ayesha will propose a beta size and invite list next week.",
      "The decision on keeping the old endpoints was deferred.",
    ],
    decisions: [
      {
        at: "04:08",
        title: "Launch moved to October 12",
        context: "Moved from October 5 after the load test showed long recordings process too slowly.",
        by: "waleed",
        supersedes: "dec_pp_0918_1",
      },
    ],
    actions: [
      {
        at: "16:20",
        title: "Fix processing time for long recordings",
        who: "waleed",
        due: -1,
        status: "completed",
      },
      {
        at: "14:10",
        title: "Write a risk list for the processing fix",
        who: "hamza",
        due: -1,
        status: "completed",
      },
      {
        at: "09:30",
        title: "Send beta banner and feedback button designs",
        who: "sara",
        due: 2,
        status: "in_progress",
      },
    ],
    questions: [
      {
        at: "10:40",
        text: "Do we keep maintaining the old endpoints through the beta?",
        by: "waleed",
        status: "open",
      },
    ],
    risks: [
      {
        at: "01:10",
        title: "Processing time grows faster than linearly past 75 minutes",
        description: "Long recordings could stall the pipeline until the fix is merged.",
        severity: "high",
        by: "waleed",
      },
    ],
    moments: [
      { at: "01:10", type: "risk", title: "Long recordings process too slowly", rel: "r1" },
      { at: "04:08", type: "decision", title: "Launch moved to October 12", rel: "d1" },
      { at: "07:45", type: "commitment", title: "Ayesha will propose a beta size next week" },
      { at: "16:20", type: "commitment", title: "Waleed owns the long-recording fix", rel: "a1" },
    ],
    topics: [
      { label: "Status of the API work", from: "00:08", to: "02:50" },
      { label: "Launch date", from: "02:50", to: "05:00" },
      { label: "Beta planning", from: "06:20", to: "09:30" },
      { label: "Old endpoints and risks", from: "10:40", to: "16:20" },
    ],
  },
}
