import type { MeetingSpec } from "./spec"

export const salesDemo: MeetingSpec = {
  slug: "sales_demo",
  title: "Sales Demo",
  day: -2,
  time: "14:00",
  durationSec: 1860,
  status: "ready",
  visibility: "attendees",
  platform: "zoom",
  captureMode: "video",
  owner: "ali",
  participants: [["ali"], ["waleed"], ["fatima"]],
  tags: ["sales", "client", "pricing"],
  dealId: "deal_northstar_labs",
  sharedWithMe: true,
  lines: [
    ["ali", "00:07", "Thanks for joining, Fatima. I'll keep the slides to a minimum and show you the product itself. Waleed is here to answer anything technical."],
    ["fatima", "00:30", "Great. My team runs about twelve customer calls a day, and the notes that come out of them are inconsistent at best."],
    ["ali", "00:58", "That's exactly what we hear. Let me start from a meeting that has just ended, because that's where WIT starts to matter."],
    ["ali", "01:40", "This is the meeting brief. Decisions, action items, open questions and risks sit at the top, and the transcript is underneath as evidence."],
    ["fatima", "02:20", "I like that the summary comes first. Nobody on my team reads transcripts."],
    ["ali", "02:45", "Every item here links to the moment in the conversation it came from. If you click a decision, it jumps to the exact timestamp."],
    ["fatima", "03:30", "Can you show me one of those? I'd want to check a commitment someone made to a customer."],
    ["ali", "03:55", "Sure. Here's a commitment to send a proposal. Click it, and you're at 12:50 in the transcript with the speaker and the audio."],
    ["fatima", "05:15", "That's useful. How do my agents start a capture? Does it join the call itself?"],
    ["waleed", "05:40", "No. WIT never joins or records on its own. Your agents connect their calendar so WIT knows what's coming up, and they choose when to start capture."],
    ["fatima", "06:25", "That's a relief. My legal team asked me about that on the first call."],
    ["waleed", "06:50", "It's also why meetings are private by default. Sharing is an explicit choice for each meeting."],
    ["fatima", "08:10", "What about customer details? Our agents hear account numbers on calls."],
    ["waleed", "08:45", "Transcripts are stored under the account that captured them, and nothing is shared unless the owner shares it. We can also set retention so recordings are deleted after a number of days."],
    ["fatima", "10:20", "Good. Can I ask the product questions about a call, like what the customer asked for?"],
    ["ali", "10:50", "Yes. Let me show you. I'll ask what the client said about timelines."],
    ["ali", "12:15", "The answer cites the exact moment and gives you a jump link. You can verify it instead of trusting it."],
    ["fatima", "13:40", "That's the part I care about most. I need to verify, not just trust."],
    ["fatima", "15:30", "Can we talk about pricing? I need to know how it works for a team of twelve."],
    ["ali", "16:00", "Of course. For twelve seats on an annual plan we would quote $12,500, which includes onboarding and the calendar integration."],
    ["fatima", "16:45", "That's in a range I can take to my director. Is there a discount for committing to two years?"],
    ["ali", "17:20", "There can be. I'd rather give you a clear picture first. Can we set up a pricing walkthrough with the details?"],
    ["fatima", "18:05", "Yes. Next Wednesday works. I'd also like my director on that call."],
    ["ali", "18:40", "Great, I'll send an invite for October 7. Waleed, could you prepare the technical details she asked about?"],
    ["waleed", "19:20", "Yes. Fatima, you mentioned exporting notes into your CRM. I'll send the API documentation for that."],
    ["fatima", "20:30", "Please do. If the export is solid, that removes my biggest blocker."],
    ["ali", "22:10", "Anything else you'd like to see before we wrap up?"],
    ["fatima", "23:00", "No, this was clear. I'll bring my director on the seventh."],
    ["ali", "24:30", "Perfect. Thanks, Fatima. You'll have the invite today."],
  ],
  insights: {
    overview:
      "Fatima Noor from Northstar Labs saw a full demo and responded well to summaries-first notes, traceable sources and manual capture. Pricing for a twelve-seat annual plan was quoted at $12,500, and a pricing walkthrough with her director was scheduled for October 7. Her main requirement is exporting notes into her CRM.",
    keyPoints: [
      "Northstar's team runs about twelve customer calls a day and wants consistent notes.",
      "Source-linked insights and manual capture addressed her main concerns.",
      "A twelve-seat annual plan was quoted at $12,500.",
      "A CRM export is her biggest blocker.",
    ],
    decisions: [
      {
        at: "18:05",
        title: "Pricing walkthrough with Northstar's director on October 7",
        by: "fatima",
      },
    ],
    actions: [
      {
        at: "18:40",
        title: "Send invite for the October 7 pricing walkthrough",
        who: "ali",
        due: 1,
        status: "open",
      },
      {
        at: "19:20",
        title: "Send API documentation for CRM export",
        who: "waleed",
        due: 6,
        status: "open",
      },
    ],
    questions: [
      {
        at: "16:45",
        text: "Is there a discount for committing to two years?",
        by: "fatima",
        status: "open",
      },
    ],
    risks: [
      {
        at: "20:30",
        title: "CRM export must work well or the deal is blocked",
        severity: "medium",
        by: "fatima",
      },
    ],
    moments: [
      { at: "02:20", type: "insight", title: "Summary-first notes resonate; nobody reads transcripts" },
      { at: "13:40", type: "insight", title: "She needs to verify AI answers, not just trust them" },
      { at: "16:00", type: "insight", title: "Twelve-seat annual plan quoted at $12,500" },
      { at: "18:05", type: "decision", title: "Pricing walkthrough set for October 7", rel: "d1" },
      { at: "19:20", type: "commitment", title: "Waleed will send CRM export documentation", rel: "a2" },
    ],
    topics: [
      { label: "Customer context", from: "00:07", to: "00:58" },
      { label: "Product demo", from: "00:58", to: "13:40" },
      { label: "Privacy and capture", from: "05:15", to: "10:20" },
      { label: "Pricing", from: "15:30", to: "18:40" },
      { label: "Next steps", from: "18:40", to: "24:30" },
    ],
  },
}
