import type { MeetingSpec } from "./spec"

export const sprintPlanning: MeetingSpec = {
  slug: "sprint_planning",
  title: "Sprint Planning",
  day: 0,
  time: "08:50",
  durationSec: 1800,
  status: "understanding",
  visibility: "team",
  platform: "google_meet",
  captureMode: "audio",
  owner: "hamza",
  participants: [["hamza"], ["waleed"], ["ahmed"], ["ayesha"], ["sara"]],
  tags: ["sprint", "engineering"],
  sharedWithMe: true,
  processing: {
    status: "understanding",
    steps: [
      { id: "upload", status: "complete" },
      { id: "transcribe", status: "complete" },
      { id: "understand", status: "active" },
      { id: "extract_decisions", status: "pending" },
      { id: "extract_actions", status: "pending" },
    ],
    startedAt: "2026-10-01T09:22:00+05:00",
  },
  lines: [
    ["hamza", "00:06", "Let's get through the sprint scope. We have ten working days and one hard launch date, so I'd like to be strict about what goes in."],
    ["ayesha", "00:30", "The priorities are the API integration, the beta onboarding flow, and rate limits. Everything else is optional."],
    ["waleed", "00:58", "The integration is the biggest item. I'd estimate eight days, with two days of buffer for the auth dependency."],
    ["ahmed", "01:30", "That's most of your sprint. Is anyone else going to touch the dashboard?"],
    ["hamza", "01:55", "I can take the loading states and the pagination. That leaves Waleed focused on the endpoints."],
    ["sara", "02:25", "I'll need the loading states by next Wednesday to run the accessibility check."],
    ["hamza", "02:50", "That works. I'll finish pagination first, since the list is the first thing people see."],
    ["ayesha", "03:30", "What about the feedback button? Is that in or out?"],
    ["sara", "03:55", "The design is finished. It's about a day of front-end work."],
    ["hamza", "04:20", "Put it in. It's small, and the beta depends on feedback."],
    ["waleed", "05:00", "Rate limits are two days. I'd propose Hamza takes those after pagination."],
    ["hamza", "05:25", "Fine. I'll do them in the second week."],
    ["ahmed", "06:10", "Let's talk capacity. Who's out in the next two weeks?"],
    ["ayesha", "06:40", "I'm out on Friday the ninth. Everyone else is here."],
    ["waleed", "07:10", "I'll have a few hours of interviews in the second week for the backend role."],
    ["ahmed", "07:50", "Okay. Account for those in the estimates."],
    ["hamza", "09:00", "Do we want to put the old endpoint cleanup in this sprint?"],
    ["ahmed", "09:30", "No. We freeze them and remove them after the beta is stable."],
    ["hamza", "10:10", "Understood. I'll move that ticket to next sprint."],
    ["sara", "11:30", "One more thing. Can we get the beta banner copy approved this sprint?"],
    ["ayesha", "12:00", "I'll review the copy tomorrow and send comments."],
    ["waleed", "13:40", "Should we agree on a definition of done for the integration? I'd say merged, tested in staging, and behind the flag."],
    ["ahmed", "14:20", "Add a production-sized performance test to that."],
    ["waleed", "14:50", "Yes, I'll include it."],
    ["hamza", "16:20", "Alright. Let me read back the sprint. Integration, pagination, loading states, feedback button, rate limits."],
    ["ayesha", "17:10", "That matches what I wrote down."],
    ["ahmed", "18:00", "Good. Let's start. Thanks, everyone."],
  ],
}
