import type { MeetingSpec } from "./spec"

export const weeklyOneOnOne: MeetingSpec = {
  slug: "weekly_11",
  title: "Weekly 1:1",
  day: -3,
  time: "16:00",
  durationSec: 1500,
  status: "ready",
  visibility: "private",
  platform: "google_meet",
  captureMode: "audio",
  owner: "waleed",
  participants: [["waleed"], ["ahmed"]],
  tags: ["oneOnOne"],
  sharedWithMe: false,
  lines: [
    ["ahmed", "00:08", "How's the week been? I know the API work has taken most of it."],
    ["waleed", "00:22", "It has. The integration is bigger than I estimated, but I think I can see the end of it. My main concern is the auth dependency."],
    ["ahmed", "00:58", "I'm aware. I'll push the platform team for a date. What else is on your mind?"],
    ["waleed", "01:25", "Workload, honestly. I'm carrying the API integration and the capture flow tests, and I don't want either to slip."],
    ["ahmed", "02:05", "Fair. The capture-flow tests can move to Hamza. They're mostly a timer problem, and he knows the pattern."],
    ["waleed", "02:40", "That helps a lot. I'll hand over my notes today."],
    ["ahmed", "03:15", "Good. Let's make you the single owner of the API integration, so there's no ambiguity about who decides."],
    ["waleed", "03:50", "Agreed. I'd rather own it fully than split it."],
    ["ahmed", "05:10", "On growth, have you thought about what you want from the next six months?"],
    ["waleed", "05:45", "I want to lead a larger piece of work. This launch is a good example. I'd like to be the person who scopes the next one."],
    ["ahmed", "06:30", "That's reasonable. Write down what scoping the next release would look like, and we'll use it to plan."],
    ["waleed", "07:10", "I'll write that up before our next one-on-one."],
    ["ahmed", "08:20", "One piece of feedback. Your updates in the planning meetings are clear, but you sometimes wait too long to raise risks."],
    ["waleed", "09:00", "That's fair. With auth, I knew about the delay for two days before I said anything."],
    ["ahmed", "09:40", "Raise them early, even if you're not sure. It's easier to adjust a plan in advance."],
    ["waleed", "10:30", "Understood. I'll flag risks in the team channel the same day."],
    ["ahmed", "12:05", "Separately, I'd like you to meet the platform team lead. You'll be working with them more."],
    ["waleed", "12:40", "Happy to. Can you introduce us this week?"],
    ["ahmed", "13:10", "I'll send the introduction tomorrow."],
    ["waleed", "15:00", "On a personal note, I'm planning a few days off in November. I'll put the dates in the calendar."],
    ["ahmed", "15:40", "Thanks for the notice. Just make sure the launch work is handed over before you go."],
    ["waleed", "18:30", "Of course. Anything else from your side?"],
    ["ahmed", "19:10", "No, that's it. Good work on the load test last week."],
    ["waleed", "20:00", "Thanks. See you next week."],
  ],
  insights: {
    overview:
      "Waleed raised workload concerns while carrying both the API integration and the capture-flow tests. Ahmed agreed to move the tests to Hamza and make Waleed the single owner of the API integration. They also discussed growth goals, early risk reporting and an introduction to the platform team lead.",
    keyPoints: [
      "Capture-flow tests move to Hamza so Waleed can focus on the API integration.",
      "Waleed is the single owner of the API integration.",
      "Raise risks early and in the team channel the same day.",
      "Waleed will write up what scoping the next release would look like.",
    ],
    decisions: [
      {
        at: "03:15",
        title: "Waleed is the single owner of the API integration",
        by: "ahmed",
      },
      {
        at: "02:05",
        title: "Capture-flow test work moves to Hamza",
        by: "ahmed",
      },
    ],
    actions: [
      {
        at: "07:10",
        title: "Write up what scoping the next release would look like",
        who: "waleed",
        due: 7,
        status: "open",
      },
      {
        at: "13:10",
        title: "Introduce Waleed to the platform team lead",
        who: "ahmed",
        due: 1,
        status: "open",
      },
      {
        at: "02:40",
        title: "Hand over capture-flow test notes to Hamza",
        who: "waleed",
        due: 0,
        status: "completed",
      },
    ],
    questions: [],
    risks: [
      {
        at: "01:25",
        title: "Workload across the API integration and capture-flow tests",
        severity: "medium",
        by: "waleed",
      },
    ],
    moments: [
      { at: "03:15", type: "decision", title: "Single ownership of the API integration", rel: "d1" },
      { at: "08:20", type: "insight", title: "Raise risks earlier" },
      { at: "10:30", type: "commitment", title: "Waleed will flag risks the same day" },
    ],
    topics: [
      { label: "Workload", from: "00:08", to: "05:10" },
      { label: "Growth", from: "05:10", to: "08:20" },
      { label: "Feedback", from: "08:20", to: "12:05" },
      { label: "Logistics", from: "12:05", to: "20:00" },
    ],
  },
}
